
print('Hola amigo')
nombre = input('como te llamas?')

print('te propongo un reto, ' + nombre)
print('piensa un numero al azar')
print('...')
print('...')
print('...')
numero1 = int(input('bien, escribe el numero'))
print('...')
print ('ahora piensa otro')
print('...')
print('...')
numero2 = int(input('tranquilo, tomtate tu tiempo y escribemelo'))
print('...')
numero3 = int(input('si si, otra mas va, dime otro numero mas'))
print('...')
print('...')
print('...')
print('que te pensabas que iva a adivinarte el futuro con solo tres numeros?')
print('...')
print('Ay ' + nombre +'!')
print('que ilusos sois los humanos...')
print('...')
print('...')
mayor = str(max(numero1, numero2, numero3))
menor = str(min(numero1, numero2, numero3))
print(('conformate sabiendo que el numero mas grande de los tres es ') + mayor)
print('...')
print(('y que el numero mas pequeño es ') + menor)
print('...')
print('y el futuro dejaselo a las gitanas del parque del retiro ')
print('...')
print('Adios ' + nombre + ', feliz ignorancia')
print('...')
print('...')
print('...')

